### ISSUE TITLE
order the orgs by contribution level

### ISSUE THREAD

**Issue by adamjonas** [bitcoin-dev-project/gh-stats#48]
<img width="716" alt="Screenshot 2023-11-03 at 10 37 19 AM" src="https://github.com/bitcoin-dev-project/gh-stats/assets/755825/57f6c637-2011-4d94-80fa-eb8ccb3507f7">

and display all of them. We don't need to hide any of them.

**Comment by Extheoisah** [comment]
So no need for the more button if we're displaying all?

**Comment by adamjonas** [comment]
Correct
